"""add_missing_columns

Revision ID: 18bfa5c44ca4
Revises: 554d80bbf11d
Create Date: 2025-04-27 11:37:19.790277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bfa5c44ca4'
down_revision = '554d80bbf11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dest_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dest_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_plan', schema=None) as batch_op:
        batch_op.drop_column('dest_lng')
        batch_op.drop_column('dest_lat')

    # ### end Alembic commands ###
