"""Initial migration

Revision ID: 554d80bbf11d
Revises: 
Create Date: 2025-04-26 18:15:32.680350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554d80bbf11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('home_address', sa.String(length=200), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emotional_rating', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lng', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('interests', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('travel_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travel_plan_id'], ['travel_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_plan_id', sa.Integer(), nullable=False),
    sa.Column('shared_email', sa.String(length=120), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['travel_plan_id'], ['travel_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_share')
    op.drop_table('photo')
    op.drop_table('memory_tag')
    op.drop_table('itinerary_item')
    op.drop_table('travel_plan')
    op.drop_table('memory')
    op.drop_table('user')
    # ### end Alembic commands ###
