"""Add home location fields to user

Revision ID: manual_add_home_fields
Revises: 18bfa5c44ca4
Create Date: 2025-04-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'manual_add_home_fields'
down_revision = '18bfa5c44ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('home_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('home_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('home_lng')
        batch_op.drop_column('home_lat')
        batch_op.drop_column('home_address')

    # ### end Alembic commands ###
